// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {config} from '../models';

export function ApplyConflictRound(arg1:string):Promise<domain.OrganizePlan>;

export function CanExecuteOrganize():Promise<domain.CanExecuteResult>;

export function CancelDeepScan():Promise<void>;

export function CancelSkillTranslation():Promise<void>;

export function CompleteOnboarding():Promise<void>;

export function ConfirmAddWorkdirs(arg1:Array<string>):Promise<domain.AddWorkdirsResult>;

export function CreateGroup(arg1:string):Promise<void>;

export function CreateSkill(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CreateSkillDir(arg1:domain.SkillVersionRef,arg2:string):Promise<void>;

export function CreateSkillFile(arg1:domain.SkillVersionRef,arg2:string):Promise<void>;

export function DeepScanSkills():Promise<Array<domain.SkillEntry>>;

export function DeleteGroup(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DeleteSkillEntry(arg1:domain.SkillVersionRef,arg2:string):Promise<void>;

export function DeleteSkillLanguage(arg1:string,arg2:string):Promise<void>;

export function DisableAllSkillLinks(arg1:Array<string>):Promise<domain.BulkLinkResult>;

export function EnableSkillLinks(arg1:Array<string>,arg2:string):Promise<domain.BulkLinkResult>;

export function ExecuteOrganize():Promise<domain.OrganizeReport>;

export function ExportSkills(arg1:Array<string>):Promise<domain.ExportToolSkillsResult>;

export function ExportToolSkills(arg1:string):Promise<domain.ExportToolSkillsResult>;

export function GetConfig():Promise<config.Config>;

export function GetConfigLoadError():Promise<string>;

export function GetLinkSnapshot(arg1:string):Promise<config.LinkSnapshot>;

export function GetSkillI18n(arg1:string):Promise<domain.SkillI18nInfo>;

export function GetSkillUsageSummary():Promise<domain.SkillUsageSummary>;

export function ImportSkills(arg1:Array<string>):Promise<domain.ImportSkillsResult>;

export function IsElevated():Promise<boolean>;

export function ListGroups():Promise<Array<domain.GroupInfo>>;

export function ListSkillFiles(arg1:domain.SkillVersionRef):Promise<Array<string>>;

export function ListSkills():Promise<Array<domain.SkillEntry>>;

export function ListTrash():Promise<Array<domain.TrashItem>>;

export function LogClientEvent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function LogsDir():Promise<string>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenLogsFolder():Promise<void>;

export function PreviewOrganize():Promise<domain.OrganizePlan>;

export function PreviewRestoreOrphanLinks():Promise<Array<domain.RestoreOrphanItem>>;

export function PurgeTrash(arg1:string):Promise<void>;

export function ReadConflictFileTexts(arg1:string,arg2:string):Promise<domain.ConflictFileTexts>;

export function ReadSkillFile(arg1:domain.SkillVersionRef,arg2:string):Promise<string>;

export function RenameGroup(arg1:string,arg2:string):Promise<void>;

export function RenameSkill(arg1:string,arg2:string):Promise<void>;

export function RenameSkillEntry(arg1:domain.SkillVersionRef,arg2:string,arg3:string):Promise<void>;

export function RequestElevation():Promise<void>;

export function ResetConflict(arg1:string):Promise<domain.OrganizePlan>;

export function RestoreOrphanLinks(arg1:Array<string>):Promise<domain.RestoreOrphanReport>;

export function RestoreTrash(arg1:string,arg2:boolean):Promise<void>;

export function RetagSkillDefaultLanguage(arg1:string,arg2:string):Promise<void>;

export function RevealInFolder(arg1:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SelectDirectory(arg1:string,arg2:string):Promise<string>;

export function SetCollapsedSkillGroups(arg1:Array<string>):Promise<void>;

export function SetConflictFileChoice(arg1:string,arg2:string,arg3:string,arg4:string):Promise<domain.OrganizePlan>;

export function SetSkillDefaultLanguage(arg1:string,arg2:string):Promise<void>;

export function SetSkillGroup(arg1:string,arg2:string):Promise<void>;

export function SetSkillLink(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetSkillOriginalLanguage(arg1:string,arg2:string):Promise<void>;

export function SetSkillsLayout(arg1:string):Promise<void>;

export function ShouldShowOnboarding():Promise<boolean>;

export function SkipConflict(arg1:string):Promise<domain.OrganizePlan>;

export function StartSkillTranslation(arg1:string):Promise<string>;

export function TranslateSkillDescription(arg1:string):Promise<string>;

export function UpdateOrganizePlan(arg1:domain.OrganizePlan):Promise<void>;

export function WriteSkillFile(arg1:domain.SkillVersionRef,arg2:string,arg3:string):Promise<void>;
