// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyConflictRound(arg1) {
  return window['go']['main']['App']['ApplyConflictRound'](arg1);
}

export function CanExecuteOrganize() {
  return window['go']['main']['App']['CanExecuteOrganize']();
}

export function CancelDeepScan() {
  return window['go']['main']['App']['CancelDeepScan']();
}

export function CancelSkillTranslation() {
  return window['go']['main']['App']['CancelSkillTranslation']();
}

export function ConfirmAddWorkdirs(arg1) {
  return window['go']['main']['App']['ConfirmAddWorkdirs'](arg1);
}

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function CreateSkill(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateSkill'](arg1, arg2, arg3, arg4);
}

export function CreateSkillDir(arg1, arg2) {
  return window['go']['main']['App']['CreateSkillDir'](arg1, arg2);
}

export function CreateSkillFile(arg1, arg2) {
  return window['go']['main']['App']['CreateSkillFile'](arg1, arg2);
}

export function DeepScanSkills() {
  return window['go']['main']['App']['DeepScanSkills']();
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DeleteSkillEntry(arg1, arg2) {
  return window['go']['main']['App']['DeleteSkillEntry'](arg1, arg2);
}

export function DeleteSkillLanguage(arg1, arg2) {
  return window['go']['main']['App']['DeleteSkillLanguage'](arg1, arg2);
}

export function DisableAllSkillLinks(arg1) {
  return window['go']['main']['App']['DisableAllSkillLinks'](arg1);
}

export function EnableSkillLinks(arg1, arg2) {
  return window['go']['main']['App']['EnableSkillLinks'](arg1, arg2);
}

export function ExecuteOrganize() {
  return window['go']['main']['App']['ExecuteOrganize']();
}

export function ExportSkills(arg1) {
  return window['go']['main']['App']['ExportSkills'](arg1);
}

export function ExportToolSkills(arg1) {
  return window['go']['main']['App']['ExportToolSkills'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigLoadError() {
  return window['go']['main']['App']['GetConfigLoadError']();
}

export function GetLinkSnapshot(arg1) {
  return window['go']['main']['App']['GetLinkSnapshot'](arg1);
}

export function GetSkillI18n(arg1) {
  return window['go']['main']['App']['GetSkillI18n'](arg1);
}

export function GetSkillUsageSummary() {
  return window['go']['main']['App']['GetSkillUsageSummary']();
}

export function ImportSkills(arg1) {
  return window['go']['main']['App']['ImportSkills'](arg1);
}

export function IsElevated() {
  return window['go']['main']['App']['IsElevated']();
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListSkillFiles(arg1) {
  return window['go']['main']['App']['ListSkillFiles'](arg1);
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function ListTrash() {
  return window['go']['main']['App']['ListTrash']();
}

export function LogClientEvent(arg1, arg2, arg3) {
  return window['go']['main']['App']['LogClientEvent'](arg1, arg2, arg3);
}

export function LogsDir() {
  return window['go']['main']['App']['LogsDir']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenLogsFolder() {
  return window['go']['main']['App']['OpenLogsFolder']();
}

export function PreviewOrganize() {
  return window['go']['main']['App']['PreviewOrganize']();
}

export function PreviewRestoreOrphanLinks() {
  return window['go']['main']['App']['PreviewRestoreOrphanLinks']();
}

export function PurgeTrash(arg1) {
  return window['go']['main']['App']['PurgeTrash'](arg1);
}

export function ReadConflictFileTexts(arg1, arg2) {
  return window['go']['main']['App']['ReadConflictFileTexts'](arg1, arg2);
}

export function ReadSkillFile(arg1, arg2) {
  return window['go']['main']['App']['ReadSkillFile'](arg1, arg2);
}

export function RenameGroup(arg1, arg2) {
  return window['go']['main']['App']['RenameGroup'](arg1, arg2);
}

export function RenameSkill(arg1, arg2) {
  return window['go']['main']['App']['RenameSkill'](arg1, arg2);
}

export function RenameSkillEntry(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameSkillEntry'](arg1, arg2, arg3);
}

export function RequestElevation() {
  return window['go']['main']['App']['RequestElevation']();
}

export function ResetConflict(arg1) {
  return window['go']['main']['App']['ResetConflict'](arg1);
}

export function RestoreOrphanLinks(arg1) {
  return window['go']['main']['App']['RestoreOrphanLinks'](arg1);
}

export function RestoreTrash(arg1, arg2) {
  return window['go']['main']['App']['RestoreTrash'](arg1, arg2);
}

export function RetagSkillDefaultLanguage(arg1, arg2) {
  return window['go']['main']['App']['RetagSkillDefaultLanguage'](arg1, arg2);
}

export function RevealInFolder(arg1) {
  return window['go']['main']['App']['RevealInFolder'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectDirectory(arg1, arg2) {
  return window['go']['main']['App']['SelectDirectory'](arg1, arg2);
}

export function SetCollapsedSkillGroups(arg1) {
  return window['go']['main']['App']['SetCollapsedSkillGroups'](arg1);
}

export function SetConflictFileChoice(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetConflictFileChoice'](arg1, arg2, arg3, arg4);
}

export function SetSkillDefaultLanguage(arg1, arg2) {
  return window['go']['main']['App']['SetSkillDefaultLanguage'](arg1, arg2);
}

export function SetSkillGroup(arg1, arg2) {
  return window['go']['main']['App']['SetSkillGroup'](arg1, arg2);
}

export function SetSkillLink(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSkillLink'](arg1, arg2, arg3);
}

export function SetSkillOriginalLanguage(arg1, arg2) {
  return window['go']['main']['App']['SetSkillOriginalLanguage'](arg1, arg2);
}

export function SetSkillsLayout(arg1) {
  return window['go']['main']['App']['SetSkillsLayout'](arg1);
}

export function SkipConflict(arg1) {
  return window['go']['main']['App']['SkipConflict'](arg1);
}

export function StartSkillTranslation(arg1) {
  return window['go']['main']['App']['StartSkillTranslation'](arg1);
}

export function TranslateSkillDescription(arg1) {
  return window['go']['main']['App']['TranslateSkillDescription'](arg1);
}

export function UpdateOrganizePlan(arg1) {
  return window['go']['main']['App']['UpdateOrganizePlan'](arg1);
}

export function WriteSkillFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteSkillFile'](arg1, arg2, arg3);
}
